services:
  package-managment-app:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: package-managment-app
    ports:
      - "8080:8080"
    networks:
      - package-managment

networks:
  package-managment:
    driver: bridge