services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: package-managment
    ports:
      - "27017:27017"
    networks:
      - package-managment
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d  # 👈 Mounts seed script

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: package-managment
      ME_CONFIG_BASICAUTH_USERNAME: package-managment
      ME_CONFIG_BASICAUTH_PASSWORD: package-managment
    networks:
      - package-managment

networks:
  package-managment:
    driver: bridge